  services:
    backend:
      build: ./POSBackend
      ports:
        - "3001:3001"
      env_file:
        - .env 

    frontend:
      build: ./POSFrontend
      ports:
        - "5173:5173"
      depends_on:
        - backend